services:
  movies-api:
    build:
      context: .
      dockerfile: Dockerfile.layered
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_DATASOURCE_URL: jdbc:postgresql://movies-db:5432/appdb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "18080:8080"
    restart: always
    depends_on:
      - movies-db


#  movies-ui-nextjs:
#    container_name: movies-ui-nextjs
#    build:
#      context: movies-ui-nextjs
#      dockerfile: Dockerfile
#    ports:
#      - "13000:3000"
#    environment:
#      SERVER_SIDE_API_BASE_URL: http://movies-api:8080
#      CLIENT_SIDE_API_BASE_URL: http://localhost:18080
