services:
  movies-api:
    build:
      context: .
      dockerfile: Dockerfile.layered
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_DATASOURCE_URL: jdbc:postgresql://movies-db:5432/appdb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "18080:8080"
    restart: always
    depends_on:
      - movies-db


  movies-api-ui:
    container_name: movies-api-ui
    build:
      context: movies-api-ui
      dockerfile: Dockerfile
    ports:
      - "13000:3000"
    environment:
      - NEXT_PUBLIC_SERVER_URL=http://movie-api:8080
      - NEXT_PUBLIC_CLIENT_URL=http://localhost:8080 #only because working locally (no DNS)
      - API_URL_TEST=http://localhost:18080
