apiVersion: v1
kind: ConfigMap
metadata:
  name: movies-config
data:
  postgres_host: postgres-service
  postgres_port: "5432"
  postgres_db: appdb

---

apiVersion: v1
kind: Secret
metadata:
  name: movies-secrets
type: Opaque
data:
  postgres_password: YWRtaW4=
  postgres_username: YWRtaW4=
