apiVersion: v1
kind: Service
metadata:
  name: movies-ui-service
spec:
  type: NodePort
  selector:
    app: movies-ui-pod
  ports:
    - name: app-port-mapping
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30030

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies-ui-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movies-ui-pod
  template:
    metadata:
      labels:
        app: movies-ui-pod
    spec:
      containers:
        - name: movies
          image: musimar/movies-api-ui
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_SERVER_URL
              value: http://movies-api-service:8080
            - name: NEXT_PUBLIC_CLIENT_URL
              value: http://localhost:8080
            - name: API_URL
              value: http://movies-api-service:8080