apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies-api
  labels:
    app: movies-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movies-api
  template:
    metadata:
      labels:
        app: movies-api
    spec:
      containers:
      - image: musimar/movies-api
        name: movies-api

